module Permutations

from "array" include Array
from "wasi/process" include Process
from "result" include Result
from "string" include String

let rec printPermutations = (a, n) => {
  if (n == 0) {
    print(Array.join("\t", a))
  }
  else {
    for(let mut i = 0; i < n; i += 1) {
      printPermutations(a, n-1)
      let mut j = i
      if (n % 2 == 0) {
        j = 0
      }
      let temp = a[n]
      a[n] = a[j]
      a[j] = temp
    }
    printPermutations(a, n - 1)  
  }
}


let input = Result.unwrap(Process.argv())
if (Array.length(input) < 2) {
  print("At least one argument is required")
  Result.unwrap(Process.exit(1))
}
let phrase = Array.slice(1, input)
printPermutations(phrase, Array.length(phrase) - 1)
