HAI 1.3
  I HAS A DAY ITZ "TUESDAY"
  DAY, WTF?
    OMG "MONDAY", VISIBLE "UGHHHHHHHHHHHH"
    OMG "TUESDAY", VISIBLE "I'M EXHAUSTED"
    OMG "WEDNESDAY", VISIBLE "I CAN FEEL THE WEEKENDS"
    OMG "THURSDAY", VISIBLE "ALMOST THERE!"
    OMG "FRIDAY", VISIBLE "FEW MORE HOURS!", GTFO
    OMGWTF, VISIBLE "NO SCHOOL!!!"
  OIC
KTHXBYE
