HAI 1.3
  HOW IZ I FIBONACCI YR N
    BOTH SAEM N AN SMALLR OF N AN 1, O RLY?         BTW N <= 1
      YA RLY, FOUND YR N
    OIC
    FOUND YR SUM OF I IZ FIBONACCI YR DIFF OF N AN 1 MKAY AN I IZ FIBONACCI YR DIFF OF N AN 2 MKAY
  IF U SAY SO
  
  IM IN YR FIB UPPIN YR II TIL BOTH SAEM II AN 11
  VISIBLE I IZ FIBONACCI YR II MKAY
  IM OUTTA YR FIB
KTHXBYE
