HAI 1.3
  IM IN YR FIRST UPPIN YR Z TIL BOTH SAEM Z AN 41
    IM IN YR SECOND UPPIN YR Y TIL BOTH SAEM Y AN Z
      IM IN YR THIRD UPPIN YR X TIL BOTH SAEM X AN Y
        I HAS A W ITZ SUM OF PRODUKT OF X AN X AN PRODUKT OF Y AN Y
        BOTH SAEM W AN PRODUKT OF Z AN Z, O RLY?
          YA RLY, VISIBLE X ", " Y ", " Z
        OIC
      IM OUTTA YR THIRD
    IM OUTTA YR SECOND
  IM OUTTA YR FIRST
KTHXBYE
