(use 'clojure.test)
(is (= (type 3) Long))
(is (= (type 5.0) Double))
(is (= (type 4/7) clojure.lang.Ratio))
(is (= (type 5N) clojure.lang.BigInt))
(is (= (type 5.88M) BigDecimal))
(is (= (type "Hello
  World") String))
(is (= (type \z) Character))
(is (= (type false) Boolean))
(is (= (type nil) nil))
(is (= (type 'dog) clojure.lang.Symbol))
(is (= (type :dog) clojure.lang.Keyword))
(is (= (type Long) java.lang.Class))
(is (= (type java.lang.Class) java.lang.Class))
